/**
 * Field Manual Modernism about page: calm service standards and direct contact methods replace unsupported customer-review claims.
 */
import { useState } from "react";
import { ArrowRight, CheckCircle2, Clock3, Mail, MapPin, Phone, Send } from "lucide-react";
import { Footer, Header, PageHero } from "@/components/SiteShell";

export default function About() {
  const [sent, setSent] = useState(false);
  return <div className="site-shell"><Header /><main>
    <PageHero eyebrow="ABOUT + CONTACT" title="A smaller route. A more accountable kind of service." copy="Anchor is built for homeowners who value a well-run operation: clear information, practical time windows, and people who respect the systems behind a comfortable home." image="/manus-storage/anchor-plumbing-work_f2e1dbd9.jpg" />
    <section className="about-intro section-block"><div className="section-marker"><span>01 / WHY ANCHOR EXISTS</span><div /></div><div className="about-statement"><h2>Good home service should not require a leap of faith.</h2><div><p>Most calls begin with uncertainty: Is this urgent? Is the company actually nearby? Will the arrival window mean anything? Anchor is a portfolio demonstration of a different answer—one that makes the operational truth visible before a homeowner commits.</p><p>The result is calmer for everyone: the visitor gets an honest route, and the field team gets the right job, in the right place, with time to do it well.</p></div></div></section>
    <section className="standards-detail"><div className="standards-detail__visual"><div className="detail-line" /><span>THE ANCHOR STANDARD</span></div><div className="standards-detail__copy"><div><b>01</b><span><h3>Say what happens next</h3><p>Every interaction should lead to a known next action, not a dead-end request form.</p></span></div><div><b>02</b><span><h3>Be precise about capacity</h3><p>An appointment is not “available” unless a specific technician can hold it.</p></span></div><div><b>03</b><span><h3>Use urgency responsibly</h3><p>Emergencies receive a different route and an upfront rate note—not the same generic calendar.</p></span></div></div></section>
    <section className="contact-section" id="contact"><div className="contact-info"><span className="eyebrow">TALK TO DISPATCH</span><h2>Start with the<br /><em>right channel.</em></h2><p>For active water, loss of heat, or a true urgent event, use emergency booking so that request is triaged correctly. For general questions, call or send a concise note.</p><div className="contact-methods"><a href="tel:+14015550198"><Phone size={19} /><span><small>CALL</small><b>(401) 555-0198</b></span></a><a href="mailto:hello@anchorhomeservices.example"><Mail size={19} /><span><small>EMAIL</small><b>hello@anchorhomeservices.example</b></span></a><span><MapPin size={19} /><span><small>ROUTE</small><b>Greater Providence, RI</b></span></span><span><Clock3 size={19} /><span><small>HOURS</small><b>Mon–Sat · 7 AM–6 PM</b></span></span></div></div><div className="contact-form">{sent ? <div className="contact-sent"><CheckCircle2 size={38} /><h3>Message marked for dispatch.</h3><p>This demo form confirms the interaction locally. In a live site, it would send your note into the same team workflow as scheduling.</p><button className="text-link" type="button" onClick={() => setSent(false)}>Send another note <ArrowRight size={16} /></button></div> : <form onSubmit={(event) => { event.preventDefault(); setSent(true); }}><span className="field-label">GENERAL QUESTION</span><h3>Leave a clear note.</h3><label>Name<input required placeholder="Your name" /></label><label>Email<input required type="email" placeholder="you@example.com" /></label><label>What can we help with?<textarea required placeholder="A short description is enough." rows={4} /></label><button className="button" type="submit">Send to dispatch <Send size={16} /></button></form>}</div></section>
  </main><Footer /></div>;
}
