/**
 * Field Manual Modernism booking flow: urgent triage, coverage validation, and technician-aware capacity are made visibly accountable at every step.
 */
import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, CalendarDays, CheckCircle2, Clock3, Droplets, MapPin, ShieldAlert, ThermometerSun, TriangleAlert, UserRoundCheck, Wrench } from "lucide-react";
import { Link } from "wouter";
import { Footer, Header } from "@/components/SiteShell";
import { availableTechnicians, scheduleDates, serviceOptions, technicians, timeSlots, validateZip } from "@/lib/anchor-data";

type BookingStage = "details" | "schedule" | "confirmed";
const iconMap = { thermometer: ThermometerSun, droplet: Droplets, wind: ThermometerSun, wrench: Wrench, home: Wrench, spark: ThermometerSun };

export default function Booking() {
  const [stage, setStage] = useState<BookingStage>("details");
  const [serviceId, setServiceId] = useState("");
  const [zip, setZip] = useState("");
  const [zipChecked, setZipChecked] = useState(false);
  const [dateId, setDateId] = useState("mon");
  const [time, setTime] = useState("");
  const [techId, setTechId] = useState("");
  const service = serviceOptions.find((item) => item.id === serviceId);
  const zipResult = validateZip(zip);
  const selectedDate = scheduleDates.find((date) => date.id === dateId) ?? scheduleDates[0];
  const availableForSelected = useMemo(() => time ? availableTechnicians(dateId, time) : [], [dateId, time]);
  const selectedTech = technicians.find((tech) => tech.id === techId);

  const chooseTime = (slot: string) => {
    setTime(slot);
    const firstAvailable = availableTechnicians(dateId, slot)[0];
    setTechId(firstAvailable?.id ?? "");
  };

  const continueFromDetails = () => {
    setZipChecked(true);
    if (service && zipResult.isCovered) setStage("schedule");
  };

  const resetFlow = () => { setStage("details"); setServiceId(""); setZip(""); setZipChecked(false); setTime(""); setTechId(""); setDateId("mon"); };

  return <div className="site-shell"><Header /><main className="booking-page">
    <section className="booking-head"><div className="dispatch-rail"><span>DISPATCH DESK</span><div className="anchor-line" /></div><div><span className="eyebrow">SCHEDULE A SERVICE</span><h1>Tell us what is happening.<br /><em>We will route the rest.</em></h1></div><aside><span className="field-label">HOW THIS WORKS</span><p>We check your area first, then make available time specific to the kind of help you need.</p></aside></section>
    <div className="booking-progress" aria-label="Booking progress"><span className={stage === "details" ? "is-current" : "is-done"}><i>1</i> Job + location</span><span className={stage === "schedule" ? "is-current" : stage === "confirmed" ? "is-done" : ""}><i>2</i> Right time</span><span className={stage === "confirmed" ? "is-current" : ""}><i>3</i> Confirmed</span></div>
    {stage === "details" && <section className="booking-panel"><div className="booking-panel__main"><span className="field-label">01 / WHAT DO YOU NEED?</span><h2>Choose the closest fit.</h2><div className="issue-grid">{serviceOptions.map((item) => { const Icon = iconMap[item.icon]; return <button type="button" className={`issue-card ${serviceId === item.id ? "is-selected" : ""} ${item.emergency ? "issue-card--emergency" : ""}`} key={item.id} onClick={() => setServiceId(item.id)}><Icon size={22} /><span><b>{item.title}</b><small>{item.description}</small></span>{item.emergency && <em>Emergency</em>}</button>; })}</div><span className="field-label booking-location-label">02 / WHERE IS THE SERVICE ADDRESS?</span><label className="booking-zip"><MapPin size={19} /><input value={zip} onChange={(event) => { setZip(event.target.value.replace(/\D/g, "")); setZipChecked(false); }} inputMode="numeric" maxLength={5} placeholder="Five-digit ZIP code" /><span>Coverage check</span></label>{zipChecked && <div className={`inline-validation ${zipResult.isCovered ? "inline-validation--good" : "inline-validation--error"}`}>{zipResult.isCovered ? <><CheckCircle2 size={18} /><span><b>You are in our service area.</b> Continue to see the right availability.</span></> : <><TriangleAlert size={18} /><span><b>{zipResult.isFormatValid ? "Outside our current service area." : "Enter a complete five-digit ZIP code."}</b> We cannot offer a reliable visit at that address right now.</span></>}</div>}<button type="button" className="button booking-next" disabled={!serviceId || !zip} onClick={continueFromDetails}>Continue to availability <ArrowRight size={17} /></button></div><aside className="booking-panel__side"><span className="field-label">YOUR ROUTE</span>{service ? <><div className={service.emergency ? "route-status route-status--emergency" : "route-status"}>{service.emergency ? <ShieldAlert size={22} /> : <CalendarDays size={22} />}<span><b>{service.emergency ? "Emergency response lane" : "Standard scheduling lane"}</b><small>{service.emergency ? "We will prioritize the next truly available technician." : "You will choose from a technician’s open time."}</small></span></div><dl><div><dt>Service</dt><dd>{service.title}</dd></div><div><dt>ZIP</dt><dd>{zip || "—"}</dd></div></dl></> : <p className="muted-copy">Choose a service to see how it will be routed.</p>}<div className="help-box"><b>A different kind of booking</b><p>We do not offer a generic “open” calendar. The choice you see will be connected to a technician who has room for the job.</p></div></aside></section>}
    {stage === "schedule" && service?.emergency && <section className="emergency-booking"><div className="emergency-booking__heading"><span className="emergency-badge"><ShieldAlert size={16} />EMERGENCY RESPONSE</span><h2>We are holding the<br /><em>next available lane.</em></h2><p>Because you selected <b>{service.title.toLowerCase()}</b>, we are not asking you to wait for a standard calendar opening.</p><button type="button" className="text-link" onClick={() => setStage("details")}><ArrowLeft size={16} />Change the job details</button></div><div className="emergency-arrival"><span className="field-label">NEXT TRUE AVAILABILITY</span><div className="arrival-time"><Clock3 size={34} /><div><b>Today · within 90 minutes</b><small>Arrival window confirmed before dispatch</small></div></div><div className="arrival-tech"><div className="tech-avatar" style={{ background: "#6E4D88" }}>ER</div><span><b>Evan Ross</b><small>Emergency response technician</small></span><span className="availability-dot">Available</span></div><div className="emergency-rate"><span>Emergency dispatch rate</span><b>$179</b><small>Work outside this rate is explained before it begins.</small></div><button className="button button--danger" type="button" onClick={() => setStage("confirmed")}>Reserve emergency response <ArrowRight size={16} /></button></div></section>}
    {stage === "schedule" && service && !service.emergency && <section className="scheduler"><div className="scheduler-main"><div className="scheduler-heading"><div><span className="field-label">02 / CHOOSE A TIME</span><h2>Open time, not<br /><em>open-ended.</em></h2></div><button type="button" className="text-link" onClick={() => setStage("details")}><ArrowLeft size={16} />Change job details</button></div><div className="date-tabs" role="tablist" aria-label="Available appointment days">{scheduleDates.map((date) => <button type="button" key={date.id} className={date.id === dateId ? "is-active" : ""} onClick={() => { setDateId(date.id); setTime(""); setTechId(""); }}><b>{date.weekday}</b><span>{date.date}</span></button>)}</div><div className="time-slot-list"><span className="field-label">{selectedDate.full.toUpperCase()}</span>{timeSlots.map((slot) => { const free = availableTechnicians(dateId, slot); const unavailable = free.length === 0; return <button type="button" className={`time-slot ${time === slot ? "is-selected" : ""}`} disabled={unavailable} key={slot} onClick={() => chooseTime(slot)}><span>{slot}</span><small>{unavailable ? "Fully assigned" : `${free.length} technician${free.length > 1 ? "s" : ""} free`}</small><i /></button>; })}</div>{time && <div className="technician-picker"><span className="field-label">ASSIGN A TECHNICIAN</span><p>This time works for the people shown below. Each other technician already has a job at this exact window.</p><div className="tech-options">{availableForSelected.map((tech) => <button key={tech.id} className={techId === tech.id ? "is-selected" : ""} type="button" onClick={() => setTechId(tech.id)}><div className="tech-avatar" style={{ background: tech.color }}>{tech.initials}</div><span><b>{tech.name}</b><small>{tech.specialty}</small></span><UserRoundCheck size={18} /></button>)}</div></div>}</div><aside className="scheduler-side"><span className="field-label">BOOKING SUMMARY</span><dl><div><dt>Service</dt><dd>{service.title}</dd></div><div><dt>ZIP</dt><dd>{zip}</dd></div><div><dt>Arrival window</dt><dd>{time ? `${selectedDate.date} · ${time}` : "Choose a time"}</dd></div><div><dt>Technician</dt><dd>{selectedTech ? selectedTech.name : "Choose a window"}</dd></div></dl>{time && selectedTech && <button className="button" type="button" onClick={() => setStage("confirmed")}>Hold this time <ArrowRight size={16} /></button>}<p className="capacity-note"><CheckCircle2 size={17} />This window is linked to {selectedTech?.name ?? "a technician’s"} current schedule.</p></aside></section>}
    {stage === "confirmed" && <section className="confirmation"><div className="confirmation-mark"><CheckCircle2 size={42} /></div><span className="eyebrow">TIME HELD</span><h2>{service?.emergency ? "A response lane is reserved." : "Your appointment is on the board."}</h2><p>{service?.emergency ? "Evan will confirm your exact arrival window before leaving for the call." : `${selectedTech?.name ?? "Your selected technician"} has this service window held in their schedule. We will send the complete confirmation to the contact details you provide by phone.`}</p><div className="confirmation-ticket"><div><span>JOB</span><b>{service?.title}</b></div><div><span>{service?.emergency ? "ARRIVAL" : "WINDOW"}</span><b>{service?.emergency ? "Today · within 90 minutes" : `${selectedDate.full} · ${time}`}</b></div><div><span>TECHNICIAN</span><b>{service?.emergency ? "Evan Ross" : selectedTech?.name}</b></div></div><div className="confirmation-actions"><a className="button" href="tel:+14015550198">Call dispatch <ArrowRight size={16} /></a><button type="button" className="text-link" onClick={resetFlow}>Book another service</button></div></section>}
  </main><Footer /></div>;
}
