/**
 * Field Manual Modernism plans page: recurring care is expressed as a visible operating rhythm with concrete member pricing and an actual next visit.
 */
import { useState } from "react";
import { ArrowRight, CalendarDays, Check, CheckCircle2, ChevronDown, CircleDollarSign, ShieldCheck } from "lucide-react";
import { Footer, Header, PageHero } from "@/components/SiteShell";
import { plans } from "@/lib/anchor-data";

export default function Plans() {
  const [selected, setSelected] = useState("seasonal");
  const [email, setEmail] = useState("");
  const [subscribed, setSubscribed] = useState(false);
  const selectedPlan = plans.find((plan) => plan.id === selected) ?? plans[0];
  const subscribe = () => { if (/\S+@\S+\.\S+/.test(email)) setSubscribed(true); };
  return <div className="site-shell"><Header /><main>
    <PageHero eyebrow="MAINTENANCE PLANS" title="Care that arrives before you have to think about it." copy="A practical plan turns seasonal maintenance into a known date on the calendar—with member pricing you can compare against the usual one-time cost." image="/manus-storage/anchor-hvac-work_fd63c616.jpg" />
    <section className="plans-intro section-block"><div className="section-marker"><span>01 / MEMBERSHIP WITH A PURPOSE</span><div /></div><div className="intro-split"><h2>Do the easy work<br />before it becomes <em>urgent.</em></h2><div><p>Anchor plans are built around the moments systems change modes. We reserve the visit in advance, document what we see, and give members an earlier line into the schedule.</p><div className="value-pills"><span><CalendarDays size={17} />Auto-scheduled visits</span><span><CircleDollarSign size={17} />Member repair rates</span><span><ShieldCheck size={17} />Priority windows</span></div></div></div></section>
    <section className="plan-grid">{plans.map((plan) => <article className={`plan-card ${plan.recommended ? "plan-card--featured" : ""}`} key={plan.id}>{plan.recommended && <span className="recommended-label">MOST PRACTICAL</span>}<span className="field-label">ANCHOR {plan.name.toUpperCase()}</span><h2>{plan.name}</h2><p>{plan.description}</p><div className="price-block"><b>${plan.price}</b><span>/ month</span><small>${plan.annual} billed annually · {plan.oneTime} one-time</small></div><ul>{plan.features.map((feature) => <li key={feature}><Check size={16} />{feature}</li>)}</ul><button type="button" className={plan.recommended ? "button" : "button button--outline"} onClick={() => { setSelected(plan.id); document.getElementById("subscribe")?.scrollIntoView({ behavior: "smooth", block: "center" }); }}>Choose {plan.name} <ArrowRight size={16} /></button></article>)}</section>
    <section className="plan-subscription" id="subscribe"><div className="subscription-rail"><span>MEMBER SETUP</span><div className="anchor-line" /></div>{subscribed ? <div className="subscribed-state"><CheckCircle2 size={38} /><span className="eyebrow">PLAN ACTIVATED</span><h2>{selectedPlan.name} is on your schedule.</h2><p>Your first auto-scheduled visit has been generated. You will receive a confirmation link before we arrive.</p><div className="next-visit"><CalendarDays size={23} /><span><small>NEXT AUTO-SCHEDULED VISIT</small><b>{selectedPlan.nextVisit}</b><em>Spring cooling tune-up · Technician assigned closer to date</em></span></div><button type="button" className="text-link" onClick={() => setSubscribed(false)}>Choose another plan</button></div> : <><div className="subscription-copy"><span className="eyebrow">START A PLAN</span><h2>Choose the rhythm<br />that fits your <em>home.</em></h2><p>There is no vague “membership submitted” state here. Once you start, we show the first visit this plan creates.</p></div><div className="subscription-form"><label><span className="field-label">SELECT PLAN</span><span className="select-wrap"><select value={selected} onChange={(event) => setSelected(event.target.value)}>{plans.map((plan) => <option value={plan.id} key={plan.id}>{plan.name} · ${plan.price}/month</option>)}</select><ChevronDown size={16} /></span></label><label><span className="field-label">EMAIL FOR CONFIRMATION</span><input type="email" placeholder="you@example.com" value={email} onChange={(event) => setEmail(event.target.value)} /></label><div className="next-visit"><CalendarDays size={22} /><span><small>YOUR GENERATED FIRST VISIT</small><b>{selectedPlan.nextVisit}</b><em>We will confirm the service address before finalizing.</em></span></div><button type="button" className="button" onClick={subscribe} disabled={!email}>Activate {selectedPlan.name} <ArrowRight size={16} /></button></div></>}</section>
    <section className="faq-section section-block"><div><span className="eyebrow">COMMON QUESTIONS</span><h2>Plan details,<br /><em>without the runaround.</em></h2></div><div className="faq-list"><details><summary>Can I change my plan later?<ChevronDown size={18} /></summary><p>Yes. You can move between plans before the next renewal; any confirmed upcoming visit is shown before the change is made.</p></details><details><summary>What does “priority windows” mean?<ChevronDown size={18} /></summary><p>Members see reserved scheduling capacity earlier when seasonal demand is high. It does not replace emergency triage for active leaks or loss of heat.</p></details><details><summary>Is the visit date fixed?<ChevronDown size={18} /></summary><p>The visit is auto-generated to start the process. We confirm address and access details before assigning the final technician and arrival window.</p></details></div></section>
  </main><Footer /></div>;
}
